/**
 * @fileoverview Bundled-snapshot typosquat scan for `skill_validate` (SMI-6033 Wave 1, Gap 7).
 *
 * Extracted from validate.ts as a standalone, dependency-light function so it
 * can be unit-tested directly (no ToolContext / database), mirroring
 * `validate-bundled-scan.ts`'s pattern. Loads the checked-in, release-time
 * reference-name snapshot (`packages/mcp-server/src/assets/
 * typosquat-reference-snapshot.json`, generated by
 * `scripts/generate-typosquat-snapshot.ts`) via a plain `readFileSync` — no
 * network or DB call, keeping `skill_validate` fully offline. Runs the
 * already-built `scanTyposquat()` detector (`@skillsmith/core`, SMI-595)
 * against the skill's own declared name, at the SMI-595 default `warn`
 * enforcement mode, surfacing any finding as a `warning`-severity
 * `ValidationError` (never `error` — warn-tier, non-blocking, matching the
 * indexer-side wiring's enforcement mode).
 *
 * SMI-6033 Wave 1 (cross-model review follow-up): `skill_rescan` is the OTHER
 * offline local-scan surface and had no typosquat check at all. Rather than
 * duplicate the snapshot load + detector call there, this module now exports
 * `detectTyposquatInName()` (raw `SecurityFinding[]`, the scanner-native shape
 * `skill_rescan` already works in) alongside `scanTyposquatName()` (the
 * `ValidationError` shape `skill_validate` needs). One snapshot, one cache,
 * one detector invocation policy for both tools.
 */
import { readFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { detectTyposquat, resolveTyposquatEnforcementMode } from '@skillsmith/core/security/scanner'
import type { SecurityFinding } from '@skillsmith/core'
import type { ValidationError } from './validate.types.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

/**
 * Path to bundled assets in the npm package (same dist-vs-src resolution as
 * `onboarding/install-assets.ts` — this file lives at the same `src/*`
 * depth, one level under the package root).
 */
function getAssetsDir(): string {
  const fromDistPath = join(__dirname, '..', '..', '..', 'src', 'assets')
  if (existsSync(fromDistPath)) {
    return fromDistPath
  }
  const fromSrcPath = join(__dirname, '..', 'assets')
  if (existsSync(fromSrcPath)) {
    return fromSrcPath
  }
  return fromDistPath
}

/**
 * Snapshot location. `SKILLSMITH_TYPOSQUAT_SNAPSHOT_PATH` is a TEST-ONLY
 * override seam (the repo's `SKILLSMITH_*` test-seam convention).
 *
 * It exists because the alternative — a test that backs up, overwrites, and
 * restores the real checked-in asset in place — is genuinely unsafe: any
 * parallel reader (e.g. `typosquat-reference-snapshot.test.ts`, running in a
 * sibling vitest worker) can observe a half-written file, and a run killed
 * mid-test leaves the repo holding a truncated or EMPTY snapshot. An empty
 * snapshot silently disables both offline typosquat checks, which is the exact
 * SMI-6033 bug — so a test harness must never be able to create one.
 *
 * Unset in production; `getAssetsDir()` resolves the bundled asset as before.
 */
const SNAPSHOT_PATH =
  process.env.SKILLSMITH_TYPOSQUAT_SNAPSHOT_PATH ||
  join(getAssetsDir(), 'typosquat-reference-snapshot.json')

interface TyposquatReferenceSnapshot {
  generatedAt: string | null
  source: string
  names: string[]
}

let cachedReferenceNames: ReadonlySet<string> | undefined

/**
 * Load the bundled reference-name snapshot (cached after first read — the
 * snapshot is a release-time asset, not something that changes mid-process).
 * Returns an empty set (no findings possible) if the snapshot is missing or
 * unparsable — never throws, so a corrupt/absent snapshot degrades to
 * "no typosquat check" rather than failing validation outright.
 */
function loadReferenceNames(): ReadonlySet<string> {
  if (cachedReferenceNames) return cachedReferenceNames

  try {
    const raw = readFileSync(SNAPSHOT_PATH, 'utf-8')
    const parsed = JSON.parse(raw) as TyposquatReferenceSnapshot
    cachedReferenceNames = new Set(
      Array.isArray(parsed.names) ? parsed.names.map((n) => n.toLowerCase()) : []
    )
  } catch {
    cachedReferenceNames = new Set()
  }

  return cachedReferenceNames
}

/**
 * Scan a skill's declared name against the bundled reference snapshot and
 * return the RAW scanner findings (warn mode — severity capped at medium, so
 * these are advisory and never on their own scan-failing / install-blocking).
 *
 * This is the shape `skill_rescan` consumes (it already works in
 * `SecurityFinding[]`); `scanTyposquatName()` below adapts the same findings
 * into `skill_validate`'s `ValidationError` shape. Returns `[]` when the name
 * is blank or the snapshot has no names — never throws.
 *
 * @param skillName the skill's own declared name (SKILL.md frontmatter `name`)
 */
export function detectTyposquatInName(skillName: string | undefined): SecurityFinding[] {
  if (!skillName || !skillName.trim()) return []

  const referenceNames = loadReferenceNames()
  if (referenceNames.size === 0) return []

  return detectTyposquat(skillName, referenceNames, resolveTyposquatEnforcementMode('warn'))
}

/**
 * Scan a skill's declared name (from its SKILL.md frontmatter) against the
 * bundled typosquat reference snapshot, returning a `warning`-severity
 * ValidationError per finding. No-op (returns []) when the snapshot has no
 * names (unwritten placeholder, or the frontmatter has no `name`).
 *
 * @param skillName the skill's own declared name (SKILL.md frontmatter `name`)
 */
export function scanTyposquatName(skillName: string | undefined): ValidationError[] {
  return detectTyposquatInName(skillName).map((finding) => ({
    field: 'name',
    message:
      `Possible typosquat: ${finding.message} ` +
      `See https://skillsmith.app/docs/security/scanner#typosquat`,
    severity: 'warning',
  }))
}
